### ISSUE TITLE
[제안] 프로젝트 개선 제안

### ISSUE THREAD

**Issue by SEOKKAMONI** [BSM-GG/BSM.GG-Frontend#4]
안녕하세요 준경님의 요청으로 몇가지 프로젝트 개선 제안을 해드리겠습니다!
코드적인 부분은 아닙니다 !

현재 프로젝트는 master에서 feature 브랜치를 만들어서 진행하고있지만
[git flow](https://techblog.woowahan.com/2553/)를 도입하여 master - develop - feature로 나눈다면 더 좋은 프로젝트가 될 것 같습니다 !
<img width="438" alt="image" src="https://github.com/BSM-GG/BSM.GG-Frontend/assets/102217654/0bc6bef9-a6b8-4cb4-92b3-ce2fdc189eab">

현재 pr template, issue template이 적용되어있지 않습니다 template을 만들어서 사용한다면 개발자가 pr 올릴때 정해진 틀에서 효율적으로 pr을 올릴수있게되어 개발자 경험도 향상될것같아요 !!

프로젝트 관리는 어떻게 하고 계신가요? 깃허브에 projects 탭에 가보면 칸반보드로 프로젝트를 관리하면서 한다면 더 좋은 프로젝트가 될 것 같아요 !!
[칸반보드 설명](https://asana.com/ko/resources/what-is-kanban)

[칸반보드, pr template, issue template 등 깃허브로 협업하기](https://velog.io/@younoah/%EA%B9%83%ED%97%88%EB%B8%8C-%ED%98%91%EC%97%85)

**Comment by SEOKKAMONI** [comment]
추가로 코드적인 부분은 PR을 올리셔서 리뷰어를 등록해주시면 리뷰를 하겠습니다!

**Comment by rlawnsrud0509** [comment]
넵 !

**Comment by Ubinquitous** [comment]
PR 템플릿, 이슈 템플릿은 저도 매우 좋은 생각같지만 이상진, 김준경 개발자님들이 말씀하신 사항을 보았을 때 깃 플로우를 도입할 만큼
큰 프로젝트는 아니라고 판단됩니다. 먼저 개발을 진행하는 개발자의 수도 많지 않으며, 앞서 말한 것처럼 빠르게 속전속결로 개발이
진행되는 것이 편하다면 지금 진행 중인 트렁크드베이스 전략이 더욱 적합한 브랜치 전략이라고 객관적으로 생각합니다.
굳이 트렁크드 베이스 전략을 사용하는 상태에서 급하게 깃 플로우로 브랜치 전략을 바꾼다고해서 그만한 장점이 따르는지에 대해서는 잘 모르겠습니다.

깃허브 프로젝트도 마찬가지 의견입니다~
겉핥기식으로 흉내만 내는 협업은 오히려 진행속도만 느리게 만드는 맹독이 될 수도 있다고 생각합니다.

**Comment by rlawnsrud0509** [comment]
그래도 한번 써본다면 나쁘지 않은 경험이 될것이고 차후 실전에서 맞닥뜨릴 상황을 대비하여 이렇게 준비해본다면 괜찮을거라고 생각됩니다

어제 develop 브랜치 등록햇어용 ㅎㅎ

**Comment by Ubinquitous** [comment]
이제부터 당신의 프로젝트는 끝나지 않을 것입니다...

**Comment by rlawnsrud0509** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by SEOKKAMONI** [comment]
제가 알고있는 드렁크 개발의 속도가 빨라진다는 소리는 솔직히 잘 모르겠습니다 마스터 부랜치에 바로 머지하니깐 배포가 빨라진다는건가요..? 다만 제가 이 프로젝트에 깃플로우를 사용하면 좋겠다고하는 점은 드렁크 기반 개발은 마스터 브랜치에다가 바로 머지하는 만큼 cicd가 잘 구축되어있눈 추로젝트에 적용해야한다고 생각합니다 하지만 해당 프로젝트에서는 구축되어있지얺을 뿐더러 develop에서의 충분한 테스트를 거치고 마스터 브랜치에 머지하는것이 훨씬 안전하다고 보고 있습니다 하지만 프로젝트 칸반보드 관리는 굳이 하지 않아도 되겠지만 저는 팀에 업무를 한눈에 확인 할 수 있고 해커톤처럼 빠르게 개발하고 끝낼 프로젝트가 아니라면 유지보수 할 사람도 생각하여 관리를 해보는것도 나쁘지않은 판단이라고 생각합니다

**Comment by Ubinquitous** [comment]
풀을 떠나서 한번의 작업으로 바로 마스터에 머지가 되는 것과, 여러 번의 작업으로 머지가 되는 것 중
전자가 속도가 빠르다는 것은 셈을 할 줄 아는 인간이라면 모두 알고 있는 사실입니다. 프론트엔드 기준으로
개발자가 두 명 밖에 안되는 상황에서 굳이 작업속도를 늦추기 위해 깃플로우를 도입하는 건 이해가 되지 않습니다.
트렁크 기반 개발에서는 어떤 PR이라도 빠르게 운영환경에 바로 적용할 수 있다는 장점이 있지만, 깃 플로우는 브랜치를
관리할 때 안정성이 높아진다는 것 외에는 현재 프로젝트 상황에서 도입할 이유가 없다고 생각합니다.

트렁크드 베이스 전략을 사용했을 때 속도가 빨라진다는 내용이 이해가 안되신다면, 
혹시 깃 플로우를 사용해서 작업 속도가 빠르다는 경험을 하신 적은 있나요? 
아니, 작업 속도가 느려지지 않는 경험은 해보신 적이 있나요?

저는 트렁크드 베이스를 사용하며 실제로 신속하게 개발이 진행된다는 경험을 받은 적이 있습니다.
프로젝트에서 가장 중요한 데드라인도 제대로 지키지 못하면서 깃 플로우, 프로젝트를 고집하는 상황은
그리 유쾌하진 않은 것 같습니다.

**Comment by SEOKKAMONI** [comment]
현재 프로젝트는 데드라인이 있는 프로젝트는 아닌것으로 알고있습니다 또한 말씀하신것처럼 단순 속도를 빠르게하기위해 프로젝트의 질 적인 부분을 포기하여 안정성을 떨어트린다는 부준도 잘 이해가 가지 않는 부분입니다 모든 판단은 개발자님께서 하시겠지만 저는 깃플로우가 성장을 추구하고 프로젝트에 안정성을 위해서는 현재 주니어 개발자에게는 깃플로우가 더 적합하다고 봅니다 프로젝트에 안정성이 강화된다는것운 곧 유저의 경험을 향상시킨다고 생각합니다 ~

**Comment by Ubinquitous** [comment]
트렁크드 베이스 전략을 사용한다고 해서 프로젝트 질과 안정성을 떨어뜨린다는 말은 브랜치 전략에 대해서
제대로 이해하지 못한 논리적인 비약 같습니다. 깃허브 워크플로우로 빌드와 린트 설정을 거친다면
트렁크드 베이스 전략도 깃 플로우 못지않게 안정적으로 이용할 수 있습니다

또한 방학 개학 전까지 퍼블리싱을 다 끝낸다는 기본적인 데드라인은 갖춰져있다고 들었습니다~
그리고 현재 프로젝트가 에러에 갑자기 대응해야 하는 경우나, 여러가지 시나리오가 필요한 프로젝트라곤 
잘 모르겠어요. 당장 서비스 출시도 안되는데 깃플로우, 깃 프로젝트 등 여러가지 단순히 남들에게 보여줄 수만 있는
앙꼬 없는 찐빵같은 기술들을 트렌드라는 하나의 단어로 퉁쳐가며 사용하는 이유가 있나 궁금합니다.

그리고 현재 리액트 프로젝트에서 넥스트로 마이그레이션하는 V2를 만드신다고 하니 빨리 1차적으로 배포 후
마이그레이션을 진행할 때 깃 플로우를 사용하는 게 더 도움이 되지 않을까 생각합니다~~

**Comment by rlawnsrud0509** [comment]
싸우지말ㄹ곸ㅋㅋㅋㅋㅋㅋ

**Comment by SEOKKAMONI** [comment]
배포에서의 안정성을 말한겁니다 develop 브랜치가 없다면 브랜치 두개가 이상진, 김준경 따로 개발되고있고 머지를 해야한다고 하였을때 master로 머지할텐데 이때의 안정성은 보장 할 수 없다고 생각합니다 만약 이것을 방지하려면 브랜치를 하나 더 만들어서 자식 브랜치 두개를 만들어야할텐데 그러면 이거나 그거나 이면 develop 브랜치를 만들어서 배포상의 안정성을 보장하는게 나을것같네요 저는 develop 브랜치 하나 더 만드는게 왜 속도를 비효율적으로 만든다는지 이해가 가지 않는 것 입니다~

**Comment by Ubinquitous** [comment]
깃 플로우가 단순히 develop 브랜치 하나 더 만든다고 구현이 되는 전략은 아닌 걸로 알고 있습니다~ 솔직히 이 프로젝트
CI/CD를 어떻게 구축할지를 잘 모르겠는데 버셀 등의 무료 호스팅 서비스로 대충대충 배포하는게 아닌 이상 두 명이서 동시에
개발을 진행했을 때 코드가 5000줄이 날아가고 https가 http로바뀌면서 디도스공격이 자동으로 당해지고 그런 일이 생기나요??

제일 처음으로 돌아가서 이미 개발이 시작되었고 브랜치도 다 세팅이 되어있는 타이밍에 개선이라면서 다른 브랜치 전략을 소개하는 건
방금 아이폰12 샀다고 말한 사람한테 아이폰에 대한 단점에 대해서 설명하고 차라리 삼성폰 사지~~라고 얘기하는 거랑 별 다를 바를 모르겠어요.

안정성을 보장할 수 없을지 있을지는 개발자들의 역량이고 본인들이 아는 본인들의 방식대로 트렁크드 기반으로 개발을 시작했는데
깃 플로우가 말씀하신 것처럼 그렇게 뛰어난 효율, 안정성을 가진다면 미리 잘 판단해서 처음부터 적용을 하며 진행했겠죠??

또한 깃 플로우는 해당 프로젝트에 딱히 잘 맞는 브랜치 전략이 아니라고 생각합니다. 웹 어플리케이션은 롤백되지 않고 지속적으로
제공이 되는데 여러 버전의 소프트웨어를 지원할 필요가 없습니다. 지속적으로 제공하는 소프트웨어를 만든다면 더 단순한 워크플로우를
채택하는 것이 맞고, 명시적으로 버전을 관리해야하는 소프트웨어도 아니기에 깃 플로우 도입에 대한 당위성은 말씀하신 안정성말고는 없네요.

뭐 꾸역꾸역 우겨서 깃 플로우를 사용해도 트렁크드 베이스 전략과 작업 속도가 비슷하다고 가정해보겠습니다.
그렇다면 현재 트렁크드 전략에서 깃 플로우로 바꾸었을 때 얻는 이득이 코드 충돌을 조금이나마 방지해주는 안정성 말고는 없는건가요?

그럼 브랜치가 일고여덟개씩 만들어진 현 상황에서 김치찌개 잘 먹고 있던 애한테 "김치찌개를 왜먹냐 ㅋㅋ 된장찌개가 훨씬 좋은데"라고
해서 된장찌개를 먹을 당위성이 없듯 비슷한 상황 같습니다.

물론 그렇게 말하면서 직접 된장찌개를 갖다주면 고민해볼 수는 있겠죠?
또 프로젝트가 바쁠 때 하루에 몇 번씩은 계속 배포될 수 있는 상황에서 적합하지 않은 브랜치 전략이라는게 너무 티가나요.
제 객관적인 생각이지만, release와 hotfix가 있으면 main과 develop은 뭐하는 브랜치인지, develop까지야 그렇다치고 main은
왜 있어야하는지 잘 이해가 가지 않아요.

본문부터, 브랜치 전략을 바꾼다고 해서 더 좋은 프로젝트가 될 것이라는 그 마인드는 존중은 하지만 이해는 가지 않습니다.
코드 외적으로 협업 방식에 대해서 피드백을 하자면, 회의 시간이나 협업 툴에 대해 제안하는게 더 좋았을 것 같습니다. 물론 그런 부분에 있어
계속 다시 생각해보니 깃허브 프로젝트와 관련된 건은 저도 동의하는 바입니다.

근데 깃 플로우는 진짜 이유를 모르겠네요 프로젝트 시작 전에 세팅 중 말씀하셨다면 그것도 반대지만 이정도까진 생각이 없었을 것 같습니다.

**Comment by SEOKKAMONI** [comment]
속도를 얘기해보겠습니다 코드 충돌을 조금이나마 방지해주는 안정성이라고 말씀하셨는데 코드 충돌을 해결하는데에 속도가 더 걸리지않을까라는 생각을 합니다 또한 깃플로우에는 다른 브랜치 전략들이 많이 있는것으로 알고있습니다 하지만 그들은 선택사항이라 생각하고 가장 중점이 되는 master - develop - feature만을 말씀드렸던것입니다 그리고 저는 제안을 한 것 이지 강조를 한게 아닙니다 "김치찌개를 왜먹냐 ㅋㅋ 된장찌개가 훨씬 좋은데"라고 말씀하신 부분도 우선 지금 깃플로우 전략으로 바뀌었다고 위에서 말씀하셨으니 그냥 사용하면 될 것 같습니다 조금의 코드 충돌이 개발자 경험 더 나아가 유저 경험까지 피해가 있을수있을것같습니다  release, hotfix를 말씀하시면서 develop과 main이 왜 있는지 말씀하셨는데 release와 hotfix를 두 개발자가 브랜치를 두개 만들어서 개발한다고 칠때 develop에서 테스트하고 main으로 머지하는 것으로 알고있습니다 물론 속도는 문제가 있겠지만 생각없이 마스터에 머지하여 유저를 테스트로 쓴다는것 자체가 문제가 있어보입니다

**Comment by SEOKKAMONI** [comment]
계속 하면 키보드 배틀로 밖에 이어지지않을것같아서 판단은 김준경,이상진 개발자에게 맡기겠습니다~
@rlawnsrud0509 @lsj0202

**Comment by Ubinquitous** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ코멘트남기고 혼자 클로즈 좀 웃기네요 일단 트렁크드 베이스가 유저를 테스트로 사용한다는 의견부터가
백날 이야기해봤자 토스는 이렇게함!!!같은 이야기만 하실 것 같아용 김준경씨는 계속 그대로 트렁크드베이스 쓴다고 하네요~ 
트렌드를 따라갈 수 있다론 화이팅!!

**Comment by Ubinquitous** [comment]
아니긍ㄷㅔ 유저경험 그렇게 중요시하시면서 정식 배포때 학교가 걸려잇음에도 현재까지도 무한alert 띄워놓는 웹만드신건 정말잘띄우신것같ㅏ아여까지가 장난입ㄴ다 화이팅~~

**Comment by rlawnsrud0509** [comment]
아니 X발 그만싸우라고 좀
